mod assignments;
mod attendance;
mod auth;
mod classes;
mod details;
mod disciplinary_actions;
mod grades;
mod groups;
mod levels;
mod parents;
mod rooms;
mod scans;
mod students;
mod subjects;
mod teachers;
mod timetable;

pub use assignments::load_assignments_routes;
pub use attendance::load_attendance_routes;
pub use auth::load_auth_routes;
pub use classes::load_classes_routes;
pub use details::load_details_routes;
pub use disciplinary_actions::load_disciplinary_actions_routes;
pub use grades::load_grades_routes;
pub use groups::load_groups_routes;
pub use levels::load_levels_routes;
pub use parents::load_parents_routes;
pub use rooms::load_rooms_routes;
pub use scans::load_scans_routes;
pub use students::load_students_routes;
pub use subjects::load_subjects_routes;
pub use teachers::load_teachers_routes;
pub use timetable::load_timetable_routes;
