//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use super::sea_orm_active_enums::AnnouncementCategories;
use super::sea_orm_active_enums::Audiences;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "announcements")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: Option<DateTime>,
    pub start_date: Option<DateTime>,
    pub end_date: Option<DateTime>,
    pub category: AnnouncementCategories,
    pub targets: Option<Vec<Uuid>>,
    pub attachements: Option<DateTime>,
    pub important: Option<bool>,
    pub audience: Audiences,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
