//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "countries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub country_name: String,
    pub country_initials: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::person_details::Entity")]
    PersonDetails,
    #[sea_orm(has_many = "super::states::Entity")]
    States,
}

impl Related<super::person_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonDetails.def()
    }
}

impl Related<super::states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::States.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
