//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "grading_rubrics")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assignments::Entity")]
    Assignments,
    #[sea_orm(has_many = "super::grading_criteria::Entity")]
    GradingCriteria,
}

impl Related<super::assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assignments.def()
    }
}

impl Related<super::grading_criteria::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GradingCriteria.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
