//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use super::sea_orm_active_enums::PerformanceLevels;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "grading_criteria")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub grading_rubric_id: Uuid,
    pub description: Option<String>,
    pub performance: PerformanceLevels,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::grading_rubrics::Entity",
        from = "Column::GradingRubricId",
        to = "super::grading_rubrics::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GradingRubrics,
}

impl Related<super::grading_rubrics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GradingRubrics.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
