//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod prelude;

pub mod activities;
pub mod assignments;
pub mod cities;
pub mod class_assignments;
pub mod classes;
pub mod countries;
pub mod disciplinary_actions;
pub mod districts;
pub mod events;
pub mod grading_criteria;
pub mod grading_rubrics;
pub mod groups;
pub mod lectures;
pub mod levels;
pub mod parents;
pub mod performance_level;
pub mod person_details;
pub mod persons;
pub mod pickups;
pub mod rooms;
pub mod scans;
pub mod sea_orm_active_enums;
pub mod states;
pub mod streets;
pub mod students;
pub mod subjects;
pub mod teacher_subjects;
pub mod teachers;
pub mod time_table;
pub mod users;
