//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::activities::Entity as Activities;
pub use super::announcements::Entity as Announcements;
pub use super::assignments::Entity as Assignments;
pub use super::class_assignments::Entity as ClassAssignments;
pub use super::classes::Entity as Classes;
pub use super::disciplinary_actions::Entity as DisciplinaryActions;
pub use super::events::Entity as Events;
pub use super::grades::Entity as Grades;
pub use super::grading_criteria::Entity as GradingCriteria;
pub use super::grading_rubrics::Entity as GradingRubrics;
pub use super::groups::Entity as Groups;
pub use super::lectures::Entity as Lectures;
pub use super::levels::Entity as Levels;
pub use super::parents::Entity as Parents;
pub use super::persons::Entity as Persons;
pub use super::pickups::Entity as Pickups;
pub use super::rooms::Entity as Rooms;
pub use super::scans::Entity as Scans;
pub use super::sessions::Entity as Sessions;
pub use super::students::Entity as Students;
pub use super::subjects::Entity as Subjects;
pub use super::teacher_subjects::Entity as TeacherSubjects;
pub use super::teachers::Entity as Teachers;
pub use super::time_table::Entity as TimeTable;
pub use super::users::Entity as Users;
