//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::parents::Entity as Parents;
pub use super::pickups::Entity as Pickups;
pub use super::students::Entity as Students;
pub use super::teachers::Entity as Teachers;
