//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::cities::Entity as Cities;
pub use super::contacts_informations::Entity as ContactsInformations;
pub use super::countries::Entity as Countries;
pub use super::districts::Entity as Districts;
pub use super::levels::Entity as Levels;
pub use super::parents::Entity as Parents;
pub use super::persons::Entity as Persons;
pub use super::pickups::Entity as Pickups;
pub use super::scans::Entity as Scans;
pub use super::states::Entity as States;
pub use super::streets::Entity as Streets;
pub use super::students::Entity as Students;
pub use super::subjects::Entity as Subjects;
pub use super::teachers::Entity as Teachers;
