//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "day_of_week_enum")]
pub enum DayOfWeekEnum {
    #[sea_orm(string_value = "1")]
    _1,
    #[sea_orm(string_value = "2")]
    _2,
    #[sea_orm(string_value = "3")]
    _3,
    #[sea_orm(string_value = "4")]
    _4,
    #[sea_orm(string_value = "5")]
    _5,
    #[sea_orm(string_value = "6")]
    _6,
    #[sea_orm(string_value = "7")]
    _7,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "time_table_item_type"
)]
pub enum TimeTableItemType {
    #[sea_orm(string_value = "activity")]
    Activity,
    #[sea_orm(string_value = "event")]
    Event,
    #[sea_orm(string_value = "lecture")]
    Lecture,
}
